APP_KEY: ''
APP_SECRET: ''
OAUTH_TOKEN: ''
OAUTH_TOKEN_SECRET: ''
emitkeys: "'user_screen_name','description','screen_name','location','friends_count','listed_count','followers_count','created_at','lang','statuses_count','lang'"
